# Site settings
author: Alex S
title: Make it Happen
header-img: img/home-bg.png
email: alex.sunga@fliptech.co
copyright_name: Alex S
description: > # this means to ignore newlines until "baseurl:"
  Pragmatic
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FlipTech9

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
